### PR TITLE
Update `opencensus/opencensus` dependency to `^0.7.0`

### LINKED ISSUE #17: [Fix] Issues with ramsey/uuid when installing?
Hey folks, not a bug, but a compatibility issue downstream from this package.

This is likely a newbie issue more than anything, but if you're using Laravel 7 (in my case 7.13) it requires `ramsey/uuid ^3|^4"`.

However, `opencensus/opencensus` (a dependency of this package) has its `ramsey/uuid` dependency set to `"~3"`.

Thus, you need to manually downgrade `ramsey/uuid` directly in your project PRIOR to requiring `gluedev/laravel-stackdriver` or you too could wind up in the dependency-hell I just escaped from.

Do this by running `composer require ramsey/uuid "^3"`.  Then you can proceed on and run `composer require gluedev/laravel-stackdriver`.

Again, this dependency tracing may be second nature to others... but it just gobbled up about 90 minutes of my time.  Thus, I hope this helps others.

### LINKED ISSUE #26: Not working with laravel 8
Hi, could you update package to support laravel 8?

Or if you prefer, I can submit a PR.

Thanks,
Pau

### PR DESCRIPTION
**Pull request by Sija**
Fixes #17 
Fixes #26

### CODE REVIEW

**Comment by andrewmclagan** [comment]
any chance of a merge on this?

**Comment by Sija** [comment]
@DiederikvandenB @GlueDev ping 🏓

**Comment by vincentrolfs** [comment]
@DiederikvandenB @GlueDev Please merge this :)

**Pull request merged**
